### ISSUE TITLE
training seems to loop without end

### ISSUE THREAD

**Issue by Cubey42** [tumurzakov/AnimateDiff#7]
``` 07/31/2023 19:11:36 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

{'prediction_type', 'variance_type'} was not found in config. Values will be initialized to default values.
loaded temporal unet's pretrained weights from I:\animetest\anime\animatediff\models\StableDiffusion\unet ...
{'num_class_embeds', 'use_linear_projection', 'upcast_attention', 'mid_block_type', 'only_cross_attention', 'dual_cross_attention', 'class_embed_type', 'resnet_time_scale_shift'} was not found in config. Values will be initialized to default values.
### missing keys: 560;
### unexpected keys: 0;
### Temporal Module Parameters: 417.1376 M
{'prediction_type'} was not found in config. Values will be initialized to default values.
07/31/2023 19:11:45 - INFO - __main__ - ***** Running training *****
07/31/2023 19:11:45 - INFO - __main__ -   Num examples = 1
07/31/2023 19:11:45 - INFO - __main__ -   Num Epochs = 1
07/31/2023 19:11:45 - INFO - __main__ -   Instantaneous batch size per device = 1
07/31/2023 19:11:45 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 1
07/31/2023 19:11:45 - INFO - __main__ -   Gradient Accumulation steps = 1
07/31/2023 19:11:45 - INFO - __main__ -   Total optimization steps = 1
Steps:   0%|                                                                                     | 0/1 [00:00<?, ?it/s]I:\animetest\anime\venv\lib\site-packages\torch\utils\checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
I:\animetest\anime\venv\lib\site-packages\xformers\ops\fmha\flash.py:339: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  and inp.query.storage().data_ptr() == inp.key.storage().data_ptr()
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:23<00:00,  2.17it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.08it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 44.81it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.08it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 47.02it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.08it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 49.18it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.08it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 47.74it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.09it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 48.82it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.10it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 47.53it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.09it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 48.84it/s]```

seems to just start producing samples to infinity...

**Comment by Cubey42** [comment]
I've tried a couple different methods and schedulers and learning rates but nothing seems to have any noticeable impact, to the point where I'm not entirely sure its training the motion module at all. do you have any examples of successful finetuning?

**Comment by tumurzakov** [comment]
Yes.

![0 (2)](https://github.com/tumurzakov/AnimateDiff/assets/440364/e618ae95-d7a0-4a75-b460-81cfedabd6a3)

Trained 1000 steps on 2 videos temporal_position_encoding_max_len=32 and it learned motion. Not perfect, but it works

**Comment by patrolli** [comment]
> Yes.
> 
> ![0 (2)](https://user-images.githubusercontent.com/440364/257829671-e618ae95-d7a0-4a75-b460-81cfedabd6a3.gif)
> 
> Trained 1000 steps on 2 videos temporal_position_encoding_max_len=32 and it learned motion. Not perfect, but it works

Hi, here you just tune the 'to_q' param or tune the whole motion module params?

**Comment by tumurzakov** [comment]
I'm wrong. [To-q only](https://github.com/tumurzakov/AnimateDiff/blob/680f247237dd656e9a26ad900cf97f8304eb2d19/train.py#L126) @patrolli

**Comment by tumurzakov** [comment]
I'm working on problem to stylize one video and specially overfit module with one motion. So we solving different problems. I'm still experimenting.

**Comment by patrolli** [comment]
Copy, tuning the entire motion module always produces worse results, which significantly harms the oringinal performance. I have also tried tuning only 'to_q,' but its results seem to be only slightly better than tuning the entire module :(

**Comment by Cubey42** [comment]
> Yes.
> 
> ![0 (2)](https://user-images.githubusercontent.com/440364/257829671-e618ae95-d7a0-4a75-b460-81cfedabd6a3.gif)
> 
> Trained 1000 steps on 2 videos temporal_position_encoding_max_len=32 and it learned motion. Not perfect, but it works

interesting, could I copy your .yaml for testing?

**Comment by tumurzakov** [comment]
Sure, i'll attach it tomorrow.

**Comment by aartykov** [comment]
Hey @tumurzakov , should the frames numbers of the videos be the same in the training dataset?

**Comment by tumurzakov** [comment]
No, [dataset loader](https://github.com/tumurzakov/AnimateDiff/blob/3454e0ad12a49042682597aa00afaaa3c525719c/tuneavideo/data/dataset.py#L35) will get as much frames as it needs. Main requirement that dataset videos must contain MORE frames than `video_length`

**Comment by tumurzakov** [comment]
@Cubey42 
nothing special. It configs used for training 96 frame model

```
pretrained_model_path: /content/animatediff/models/StableDiffusion/
motion_module: /content/drive/MyDrive/AI/video/videos/intro2/train/mm-100.pth
motion_module_pe_multiplier: 1
inference_config_path: /content/drive/MyDrive/AI/video/videos/intro2/infer/valid.yaml
start_global_step: 0
output_dir: /content/drive/MyDrive/AI/video/videos/intro2/train
train_data:
  video_path:
  - /content/drive/MyDrive/AI/video/videos/intro2/dataset/0.mp4
  - /content/drive/MyDrive/AI/video/videos/intro2/dataset/1.mp4
  prompt:
  - fly over mist
  - fly over mist
  n_sample_frames: 96
  width: 480
  height: 272
  sample_start_idx: 0
  sample_frame_rate: 1
validation_data:
  prompts:
  - fly over mist
  - fly over mist
  video_length: 96
  width: 480
  height: 272
  temporal_context: 96
  num_inference_steps: 20
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
learning_rate: 3.0e-05
train_batch_size: 1
max_train_steps: 1000
checkpointing_steps: 100
validation_steps: 10000
trainable_modules:
- to_q
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true
```
